name: Workflow Compartilhado

on:
  workflow_dispatch:
    inputs:
      nome-do-curso-enviado:
        required: true
        type: string

jobs:
  chama-workflow:
    uses: ./.github/workflows/trigger-workflow-call.yml@main
    with:
      nome-do-curso-enviado: ${{ inputs.nome-do-curso-enviado }}

