name: Expõe a secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Tentativa de expor uma secret
        run: echo "{{ secrets.curso_actions_secret }}"

      - name: Tentativa de expor uma secret manipulando a saída
        run: echo "{{ secrets.curso_actions_secret }}" | sed 's/./& /g'