name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "Proprietário do Repositório: ${{ github.repository_owner }}"
          echo "SHA do Commit: ${{ github.sha }}"