name: Criando nosso trigger deployment

on:
  deployment

jobs:
  job-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Printa Deployment
        run: Esse job foi triggado por um deployment externo
