name: Testando a regra de protection rule

on:
  create

jobs:
  print-branch-or-tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Aviso sobre criação da branch ou tag
        run: Uma nova branch ou tag foi criada no repositório