name: Criando nosso trigger Schedule

on:
  schedule:
    - cron: 25 01 * * 3
    - cron: 54 22 * * 3 # 19:54

jobs:
  executa-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Informa Horário
        run: echo "Schedule executado com sucesso, agora são $(date) UTC"
